### PR TITLE
Email notification on error

### LINKED ISSUE #18: Email notifications When Cron Job fails
Add a configuration to enter 1 or more email addresses to alert when a cron job fails

### PR DESCRIPTION
**Pull request by schmengler**
Email notification for errors can be configured  (resolves #18)

### CODE REVIEW

**Comment by schmengler** [comment]
email-configuration

File: Test/Integration/ErrorNotificationTest.php [hunk 1]
```diff
@@ -0,0 +1,159 @@
...
+        $this->objectManager->addSharedInstance($this->errorNotification, ErrorNotificationEmail::class);
+    }
+
+    public function testSentIfScheduleHasErrorStatusProcessedByScheduleManagement()
+    {
+        $this->markTestSkipped('Schedule management fails immediately instead of saving error status');
+        $this->givenCronjobThrows(new \Exception('Fake error message'), $executed);
+        $this->thenErrorNotificationShouldBeSentWithMessage('Fake error message');
+        $this->whenCronjobsAreProcessedByScheduleManagement();
+    }
```
Comment (Ethan3600) [inline Test/Integration/ErrorNotificationTest.php:107]: Not really a "review," but I love the way you organize integration tests. Learning a lot from your PRs!

File: etc/crontab/di.xml [hunk 2]
```diff
@@ -1,9 +1,9 @@
 <?xml version="1.0" encoding="UTF-8"?>
 <config xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="urn:magento:framework:ObjectManager/etc/config.xsd">
     <type name="Magento\Cron\Observer\ProcessCronQueueObserver">
-        <plugin name="ethanyehuda_cronjobmanager_clean_running_jobs" type="EthanYehuda\CronjobManager\Plugin\Cron\Observer\ProcessCronQueueObserverPlugin" />
+        <plugin name="ethanyehuda_cronjobmanager" type="EthanYehuda\CronjobManager\Plugin\Cron\Observer\ProcessCronQueueObserverPlugin" />
```
Comment (Ethan3600) [inline etc/crontab/di.xml:4]: Do plugin names not have to be unique?

**Comment by Ethan3600** [comment]
This looks great! I think I accidentally stopped travis from running on PRs (I just re-enabled it again). Going to close and reopen the PR to trigger tavis (hopefully this works :rofl: )

File: etc/crontab/di.xml (hunk 2 above)
Comment (schmengler) [reply etc/crontab/di.xml:4]: only for each type. and since there now are plugins that add multiple behavior, I thought it would be sensible to keep the plugin names more neutral

File: Test/Integration/ErrorNotificationTest.php (hunk 1 above)
Comment (schmengler) [reply Test/Integration/ErrorNotificationTest.php:107]: Thank you, glad to hear that! :slightly_smiling_face:

**Comment by schmengler** [comment]
When testing, we got lots of false positives of "process went away", which seems related to bug #126 - should be solved by latest commit, but I'll keep this updated

**Comment by schmengler** [comment]
Yep, that solved it! @Ethan3600 can you re-run the failed Travis builds?

**Comment by Ethan3600** [comment]
This looks great! I'm just trying to figure out why magento2.2-develop unit & integration tests are failing. Looks like composer is failing to pull it in. Not sure why.

**Comment by Ethan3600** [comment]
Seems like Travis's composer cache was corrupted. I just had to re-run the "job" for the test. Going to merge this puppy in!!

Thanks again @schmengler

**Comment by WinstonN** [comment]
@Ethan3600 Your extension is great, and I love using it. I'd like to know when you are planning to release Ethan3600:1.x-develop since I am also interested in some of the fixes in there, for example the PID fix in this issue

UPDATE: I see that this is in the 1.9.0 release - Thanks!
https://github.com/Ethan3600/magento2-CronjobManager/releases/tag/v1.9.0
